name: Fetch update

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O gdp.js https://www.iatatravelcentre.com/static/js/gdp.js
        
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install file-eval

    - uses: actions/github-script@v4
      with:
        script: |
          const fileEval = require('file-eval');
          fileEval.sync('./gdp.js');
          const content = JSON.stringify(Object.fromEntries(Object.entries(svgMapDataGPD.values).map(function(a) {
            var gdp = a[1]['gdp'];
            return [a[0], {'published':gdp.substring(10,20), 'gdp':gdp.substring(25)}];
          })), null, '\t');
          const fs = require('fs');
          try {
            const data = fs.writeFileSync('./gdp.json', content)
          } catch (err) {
            console.error(err)
          }
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fetched update
