name: Fetch update

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O gdp.js https://www.iatatravelcentre.com/static/js/gdp.js
        
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install file-eval

    - uses: actions/github-script@v4
      id: set-result
      with:
        script: |
          const fileEval = require('file-eval');
          fileEval('./gdp.js')
              .then(console.log)
              .catch(console.error);
          return JSON.stringify(Object.fromEntries(Object.entries(svgMapDataGPD.values).map(function(a) {
            var gdp = a[1]['gdp'];
            return [a[0], {'published':gdp.substring(10,20), 'gdp':gdp.substring(25)}];
          })), null, '\t');
        result-encoding: string
        
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}" >> gdp.json
                
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fetched update
